"""
PDF report generator for datasets.
"""
import io
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)


def generate_report(dataset, summary, preview):
    """Generate a PDF report for a tabular dataset. Returns bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter,
                            leftMargin=0.75 * inch, rightMargin=0.75 * inch,
                            topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle', parent=styles['Heading1'],
        fontSize=22, textColor=colors.HexColor('#1e293b'),
        spaceAfter=12,
    )
    h2_style = ParagraphStyle(
        'CustomH2', parent=styles['Heading2'],
        fontSize=14, textColor=colors.HexColor('#475569'),
        spaceAfter=8, spaceBefore=12,
    )
    body_style = styles['BodyText']

    story = []

    # Title
    story.append(Paragraph(f"Data Report: {dataset.original_filename}", title_style))
    story.append(Paragraph(
        f"Generated by DataLens • {dataset.uploaded_at.strftime('%B %d, %Y at %H:%M')}",
        styles['Italic']
    ))
    story.append(Spacer(1, 0.2 * inch))

    # Overview section
    story.append(Paragraph("Dataset Overview", h2_style))
    overview_data = [
        ['File', dataset.original_filename],
        ['Size', dataset.file_size_human],
        ['Rows', f"{summary['rows']:,}"],
        ['Columns', f"{summary['columns']:,}"],
        ['Memory', f"{summary['memory_mb']} MB"],
        ['Duplicate rows', f"{summary['duplicate_rows']:,}"],
        ['Total nulls', f"{summary['total_nulls']:,} ({summary['null_pct_total']}%)"],
    ]
    t = Table(overview_data, colWidths=[2 * inch, 4 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f1f5f9')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#475569')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.2 * inch))

    # Column details
    story.append(Paragraph("Column Details", h2_style))
    col_data = [['Column', 'Type', 'Nulls', 'Unique', 'Stats']]
    for col in summary['column_info']:
        stats = ''
        if col['kind'] == 'numeric' and 'mean' in col:
            stats = f"min={col.get('min')}, max={col.get('max')}, μ={col.get('mean')}"
        elif col['kind'] == 'categorical' and 'top_values' in col:
            top = ', '.join(v['value'] for v in col['top_values'][:2])
            stats = f"top: {top}"
        elif col['kind'] == 'datetime':
            stats = f"{col.get('min', '')} → {col.get('max', '')}"

        col_data.append([
            Paragraph(col['name'][:30], body_style),
            col['kind'],
            f"{col['null_count']} ({col['null_pct']}%)",
            f"{col['unique']:,}",
            Paragraph(stats[:50], body_style),
        ])

    col_table = Table(col_data, colWidths=[1.6 * inch, 0.9 * inch, 1.1 * inch, 0.9 * inch, 2.0 * inch])
    col_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366f1')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
    ]))
    story.append(col_table)
    story.append(PageBreak())

    # Preview
    story.append(Paragraph("Data Preview (first rows)", h2_style))
    if preview and preview.get('rows'):
        # Limit columns shown to fit page
        cols = preview['columns'][:6]
        rows_to_show = preview['rows'][:10]
        data = [cols]
        for row in rows_to_show:
            data.append([str(c)[:20] if c is not None else '—' for c in row[:6]])

        preview_table = Table(data, repeatRows=1)
        preview_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366f1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
        ]))
        story.append(preview_table)

    doc.build(story)
    buf.seek(0)
    return buf.read()
